<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
		xmlns:soap12bind="http://schemas.xmlsoap.org/wsdl/soap12/"
		xmlns:soapbind="http://schemas.xmlsoap.org/wsdl/soap/"
		xmlns:tns="http://www.fss.ru/integration/ws/fault/v01"
		xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
		xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		xmlns:xsd1="0"
		xmlns:xsd2="http://www.fss.ru/integration/types/common/v01"
		xmlns:xsd3="http://www.fss.ru/integration/types/dic/errors/v01"
		xmlns:xsd4="http://www.fss.ru/integration/types/dic/fault/v01"
		xmlns:xsd5="http://www.fss.ru/integration/types/fault/v01"
		xmlns:xsd6="http://www.fss.ru/integration/types/organization/v01"
		xmlns:xsd7="http://www.fss.ru/integration/types/sedo/v01"
		targetNamespace="http://www.fss.ru/integration/ws/fault/v01">
	<types>
		<xsd:schema xmlns:flt="http://www.fss.ru/integration/types/fault/v01"
				xmlns:tns="0"
				xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				targetNamespace="0">
			<xsd:import namespace="http://www.fss.ru/integration/types/fault/v01"
					schemaLocation="file://1.xsd"/>
		</xsd:schema>
	</types>
	<message name="DecryptException">
		<part name="decryptFault"
				element="xsd5:decryptFault"/>
	</message>
	<message name="InternalException">
		<part name="internalFault"
				element="xsd5:internalFault"/>
	</message>
	<message name="DigitalSignException">
		<part name="digitalSignFault"
				element="xsd5:digitalSignFault"/>
	</message>
</definitions>